version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_dev
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sstours
    ports:
    - "5432:5432"

volumes:
  postgres_data:
